name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://Alfonzo28.github.io/ARL
          environment: production
      - name: Install
        run: |
          npm install

      - name: Run
        run: |
          npm start

      - name: Build
        run: |
          npm run build

      - name: Deploy my app
        run: |
          npm run deploy

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://Alfonzo28.github.io/ARL
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://Alfonzo28.github.io/ARL
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}